config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships

  resources :beer_clubs

  resources :users
  resources :beers
  resources :breweries
  resource :session, only: [:new, :create, :delete]
  root 'breweries#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  post 'places', to: 'places#search'
  resources :places, only: [:index, :show]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to: 'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to: 'breweries#list'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :beer_club
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        current_user.memberships << @membership
        format.html { redirect_to beer_club_path(@membership.beer_club_id), notice: 'Wellcome to club!' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership = current_user.memberships.find(@membership.__id)
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user.id), notice: 'Membership was successfully destroyed.' }
      #  format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membership_params
    params.require(:membership).permit(:beer_club_id, :user_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :beer_club_id %><br>
    <%= f.number_field :beer_club_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-active"%>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Memberships</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Beer club</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.beer_club_id %></td>
        <td><%= membership.user_id %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path,  class:"btn btn-primary"%>

app/views/memberships/new.html.erb
<h2>New Membership</h2>

<%= form_for(@membership) do |f| %>
    <% if @membership.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@membership.errors.count, "error") %> prohibited membership from being saved:</h2>

          <ul>
            <% @membership.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.collection_select(:beer_club_id, BeerClub.all, :id, :id) %>
    <p></p>
    <%= f.submit %>

<% end %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beer club:</strong>
  <%= @membership.beer_club_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user_id %>
</p>

<%= edit_and_destroy_buttons(@membership) %>| |
<%= link_to 'Back', memberships_path %>